on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the package
        required: false
        type: string
  push:
    branches:
      - main

name: Build and Push image to GCR

jobs:
  build-push-notify:
    name: Build, push, and notify
    uses: bahasa-ai/workflows/.github/workflows/build-push-notify-lark.yml@main
    with:
      working-directory: ./
      package-name: book-meeting-ai
      version-script: 'grep -Poi " *\"version\": *\"\K[^\"]*" ./package.json '
      group-id: oc_44f7ba3511134d8f11859bf098207774
      cloud: gcp
      gcp-wif-provider: projects/1001592061233/locations/global/workloadIdentityPools/github/providers/github-bahasa-ai
      gcp-wif-sa: gh-runner-sa@audyno-prod.iam.gserviceaccount.com
      image-prefix: |
        asia-southeast1-docker.pkg.dev/audyno-prod/audyno
    secrets:
      lark-app-id: ${{ secrets.LARK_APP_ID }}
      lark-app-secret: ${{ secrets.LARK_APP_SECRET }}
      build-secrets: |
        GITHUB_ACCESS_TOKEN=${{ secrets.GPR_AUTH_TOKEN }}
